#!/usr/bin/env python3
"""
FEAT NEXUS - Setup Script
=========================
Interactive script to configure the new FEAT_NEXUS Supabase project.
This will NOT touch any existing project - it creates a fresh setup.

Usage:
    python setup_nexus_db.py
"""

import os
import sys
from pathlib import Path

# Colors for terminal
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
RESET = "\033[0m"
BOLD = "\033[1m"

def print_header():
    print()
    print(f"{CYAN}╔══════════════════════════════════════════════════════════════╗{RESET}")
    print(f"{CYAN}║          FEAT NEXUS - DATABASE SETUP WIZARD                  ║{RESET}")
    print(f"{CYAN}║          Creates fresh Supabase connection                   ║{RESET}")
    print(f"{CYAN}╚══════════════════════════════════════════════════════════════╝{RESET}")
    print()


def get_credentials():
    """Prompt user for new Supabase credentials."""
    print(f"{YELLOW}⚠️  IMPORTANTE:{RESET}")
    print("   Este script configurará un NUEVO proyecto de Supabase.")
    print("   NO afectará ningún proyecto existente.")
    print()
    print(f"{BOLD}Paso 1:{RESET} Ve a https://database.new y crea un proyecto 'FEAT_NEXUS_MAIN'")
    print(f"{BOLD}Paso 2:{RESET} Ve a Project Settings > API")
    print(f"{BOLD}Paso 3:{RESET} Copia los valores y pégalos aquí:")
    print()
    
    supabase_url = input(f"{CYAN}Project URL:{RESET} ").strip()
    if not supabase_url.startswith("https://"):
        print(f"{RED}Error: La URL debe comenzar con https://{RESET}")
        return None, None
        
    supabase_key = input(f"{CYAN}Anon/Public Key:{RESET} ").strip()
    if len(supabase_key) < 30:
        print(f"{RED}Error: La key parece muy corta. Verifica que copiaste bien.{RESET}")
        return None, None
        
    return supabase_url, supabase_key


def test_connection(url: str, key: str) -> bool:
    """Test Supabase connection."""
    print()
    print(f"{YELLOW}🔄 Probando conexión...{RESET}")
    
    try:
        from supabase import create_client, Client
        
        client: Client = create_client(url, key)
        
        # Simple test - try to query
        result = client.table("_test_connection_").select("*").limit(1).execute()
        # This will fail with "relation does not exist" which is GOOD
        # (means we connected but table doesn't exist yet)
        
    except Exception as e:
        error_msg = str(e)
        if "relation" in error_msg or "does not exist" in error_msg or "404" in error_msg:
            # This is actually success - we connected but table doesn't exist
            print(f"{GREEN}✅ Conexión exitosa! (Base de datos vacía - listo para schema){RESET}")
            return True
        elif "Invalid API key" in error_msg or "401" in error_msg:
            print(f"{RED}❌ Error: API Key inválida{RESET}")
            return False
        elif "fetch failed" in error_msg or "network" in error_msg.lower():
            print(f"{RED}❌ Error de red. Verifica la URL.{RESET}")
            return False
        else:
            # Assume it's a "table not found" type error = connection works
            print(f"{GREEN}✅ Conexión exitosa!{RESET}")
            return True
            
    print(f"{GREEN}✅ Conexión exitosa!{RESET}")
    return True


def create_env_file(url: str, key: str):
    """Create or update .env file with new credentials."""
    env_path = Path(__file__).parent / ".env"
    
    # Backup existing if any
    if env_path.exists():
        backup_path = Path(__file__).parent / ".env.backup"
        print(f"{YELLOW}📦 Respaldando .env actual a .env.backup{RESET}")
        env_path.rename(backup_path)
    
    env_content = f"""# FEAT NEXUS Configuration
# Generated by setup_nexus_db.py
# Date: {__import__('datetime').datetime.now().isoformat()}

# ════════════════════════════════════════════════════════════════
# SUPABASE - FEAT NEXUS PROJECT (Trading Bot Database)
# ════════════════════════════════════════════════════════════════
SUPABASE_URL={url}
SUPABASE_KEY={key}

# ════════════════════════════════════════════════════════════════
# MCP SERVER CONFIGURATION
# ════════════════════════════════════════════════════════════════
LOG_LEVEL=INFO
DOCKER_MODE=true

# ════════════════════════════════════════════════════════════════
# ML ENGINE CONFIGURATION
# ════════════════════════════════════════════════════════════════
EXECUTION_ENABLED=false
SHADOW_MODE=true
MIN_SAMPLES_FOR_TRAINING=1000

# ════════════════════════════════════════════════════════════════
# RAG MEMORY (ChromaDB - Local, no external API needed)
# ════════════════════════════════════════════════════════════════
CHROMA_PERSIST_DIR=/app/data/chroma
USE_LOCAL_EMBEDDINGS=true

# ════════════════════════════════════════════════════════════════
# DATA PATHS
# ════════════════════════════════════════════════════════════════
DATA_DIR=/app/data
MODELS_DIR=/app/models
"""
    
    with open(env_path, "w") as f:
        f.write(env_content)
        
    print(f"{GREEN}✅ Archivo .env creado exitosamente{RESET}")


def run_schema(url: str, key: str):
    """Execute the institutional schema on the new database."""
    schema_path = Path(__file__).parent / "institutional_schema.sql"
    
    if not schema_path.exists():
        print(f"{YELLOW}⚠️  Schema file not found. Run manually from SQL Editor.{RESET}")
        return False
        
    print()
    print(f"{YELLOW}🔄 Creando tablas en la base de datos...{RESET}")
    
    try:
        from supabase import create_client
        
        client = create_client(url, key)
        
        with open(schema_path, "r") as f:
            schema_sql = f.read()
            
        # Supabase client doesn't have raw SQL execution
        # User needs to run this manually in SQL Editor
        print(f"{YELLOW}⚠️  Para crear las tablas:{RESET}")
        print(f"   1. Ve a tu proyecto Supabase > SQL Editor")
        print(f"   2. Copia el contenido de: {schema_path}")
        print(f"   3. Ejecuta el script")
        print()
        
    except Exception as e:
        print(f"{YELLOW}⚠️  Ejecuta el schema manualmente: {e}{RESET}")
        
    return True


def print_summary(url: str):
    """Print setup summary."""
    print()
    print(f"{GREEN}{'═' * 60}{RESET}")
    print(f"{GREEN}          ✅ SETUP COMPLETADO EXITOSAMENTE{RESET}")
    print(f"{GREEN}{'═' * 60}{RESET}")
    print()
    print(f"{BOLD}Proyecto Supabase:{RESET} {url}")
    print(f"{BOLD}Archivo .env:{RESET} Creado")
    print(f"{BOLD}Embeddings:{RESET} Local (sentence-transformers, sin API externa)")
    print(f"{BOLD}Modo:{RESET} Shadow Mode (sin ejecución real)")
    print()
    print(f"{YELLOW}📋 PRÓXIMOS PASOS:{RESET}")
    print("   1. Ejecuta el schema SQL en Supabase SQL Editor")
    print("   2. Reconstruye Docker: docker-compose up --build -d")
    print("   3. Verifica con: check_system.bat")
    print()


def main():
    print_header()
    
    # Get credentials
    url, key = get_credentials()
    if not url or not key:
        print(f"{RED}Setup cancelado.{RESET}")
        sys.exit(1)
        
    # Test connection
    if not test_connection(url, key):
        print(f"{RED}No se pudo conectar. Verifica las credenciales.{RESET}")
        sys.exit(1)
        
    # Create .env
    create_env_file(url, key)
    
    # Run schema (or instructions)
    run_schema(url, key)
    
    # Summary
    print_summary(url)


if __name__ == "__main__":
    main()
